# Site settings
title: Junyoung Son
baseurl: ""
url: "https://rgop13.github.io"
google_analytics: # Tracking ID, e.g. "UA-000000-01"

# Author
author:
  name: Junyoung Son
  desc: NLP & AI Lab., Korea University
  email: s0ny@korea.ac.kr
  selfie: assets/img/profile.jpeg

# social
social:
  email:
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: rgop13
  google_plus:
  instagram:
  keybase:
  linkedin: https://www.linkedin.com/in/junyoung-son-2836a2183/
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  steam:
  tumblr:
  gitlab:
  twitter:
  vimeo:
  wordpress:
  youtube:
  default_txt: "Follow On"

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink: /:year-:month-:day/:title
#paginate_path: "/portfolio/page:num/"
#paginate: 5
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "READE.md"
  - "screenshot.png"
